version: '3'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: secret
      DB_DATABASE: reclamos
    depends_on:
      - db

  db:
    image: mariadb/server
    environment:
      MARIADB_DATABASE: reclamos
      MARIADB_ROOT_HOST: localhost
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: secret
    ports:
      - '3307:3306'
    volumes:
      - ./data:/var/lib/mysql